wandb_version: 1

track:
  desc: null
  value: true
exp_name:
  desc: null
  value: lasertag_s
wandb_project_name:
  desc: null
  value: syllabus
wandb_entity:
  desc: null
  value: rpegoud
logging_dir:
  desc: null
  value: .
_wandb:
  desc: null
  value:
    code_path: code/lasertag_sp.py
    python_version: 3.10.7
    cli_version: 0.16.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1712049343.0
    t:
      1:
      - 1
      - 2
      - 3
      - 12
      - 30
      - 55
      2:
      - 1
      - 2
      - 3
      - 12
      - 30
      - 55
      3:
      - 13
      - 16
      - 23
      - 35
      4: 3.10.7
      5: 0.16.5
      8:
      - 3
      - 5
      13: windows-amd64
